---
name: Test Ben
on:
  workflow_dispatch:
  
jobs:
  pull-repo-ben:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout tlsi-test'
        uses: actions/checkout@master
        with:
          repository: blauziere/tlsi-test
          persist-credentials: false
          fetch-depth: 0
      - name: Modify a file
        run: |
          date +%s > date.txt
          ls
      - name: 'Commit and push changes'
        with:
          github_token: ${{ secrets.BEN_TLSI_TOKEN }}
        env: 
          CI_COMMIT_MESSAGE: 'Test push Desjardins'
          CI_COMMIT_AUTHOR: 'Bob'
          CI_COMMIT_EMAIL: 'benjamin.lauziere@desjardins.com'
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push https://${{ secrets.BEN_TLSI_TOKEN }}@github.com/blauziere/tlsi-test.git
