---
name: Test Ben
on:
  workflow_dispatch:
  
jobs:
  test-pull-ext-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: aubreyphan/Hotels
          fetch-depth: 0
