---
name: Test Ben
on:
  workflow_dispatch:
  
jobs:
  pull-repo-ben:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout tlsi-test'
        uses: actions/checkout@master
        with:
          repository: blauziere/tlsi-test
          persist-credentials: false
          fetch-depth: 0
      - name: Modify a file
        run: |
          date +%s > date.txt
          ls
      - name: 'Commit and push changes'
        uses: actions-js/push@master
        with:
          repository: blauziere/tlsi-test
          github_token: ${{ secrets.BEN_TLSI_TOKEN }}
